In [8]:
import CrossTabulation as ct
import ClippingRrasterWithShp as cRs
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score


lucc1996 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB1996_WH_Erase_Merge_UGB_Dis.tif"
lucc2002 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2002_WH_Erase_Merge_UGB_Dis.tif"
lucc2005 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2005_WH_Erase_Merge_UGB_Dis.tif"
lucc2010 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2010_WH_Erase_Merge_UGB_Dis.tif"
lucc2015 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2015_WH_Erase_Merge_UGB_Dis.tif"
clipFc = r"C:\Users\jyang71\Desktop\Datasets\WH_XZQ_Project_Eliminate.shp"
gpdFc1996 = cRs.getLuccArr(lucc1996,clipFc)
gpdFc2002 = cRs.getLuccArr(lucc2002,clipFc)
gpdFc2005 = cRs.getLuccArr(lucc2005,clipFc)
gpdFc2010 = cRs.getLuccArr(lucc2010,clipFc)
gpdFc2015 = cRs.getLuccArr(lucc2015,clipFc)


shapeLength = gpdFc1996.shape[0]
result = []
for i in range(2):
	mapArr_96 = gpdFc1996.LuccMtx[i][0]
	mapArr_05 = gpdFc2005.LuccMtx[i][0]
	mapArr_10 = gpdFc2010.LuccMtx[i][0]
	mapArr_15 = gpdFc2015.LuccMtx[i][0]
	TM_9605 = ct.transMatrix(mapArr_96,mapArr_05,7)[1]
	gainIntenPtn_9605,lossIntenPtn_9605 = ct.TransPattern(TM_9605,9)
	GainLossPtn_9605 = ct.mergeGainLoss(gainIntenPtn_9605,lossIntenPtn_9605)

	TM_0510 = ct.transMatrix(mapArr_05,mapArr_10,7)[1]
	gainIntenPtn_0510,lossIntenPtn_0510 = ct.TransPattern(TM_0510,5)
	GainLossPtn_0510 = ct.mergeGainLoss(gainIntenPtn_0510,lossIntenPtn_0510)

	TM_1015 = ct.transMatrix(mapArr_10,mapArr_15,7)[1]
	gainIntenPtn_1015,lossIntenPtn_1015 = ct.TransPattern(TM_1015,5)
	GainLossPtn_1015 = ct.mergeGainLoss(gainIntenPtn_1015,lossIntenPtn_1015)

	finnalPtn = ct.mergeInterval(GainLossPtn_9605,GainLossPtn_0510,GainLossPtn_1015)
	result.append(finnalPtn)


C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:56: RuntimeWarning: invalid value encountered in double_scalars
  gainIntensity_ji = (arr[j][i]/duration)/np.sum(arr[j,:])
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:59: RuntimeWarning: invalid value encountered in greater_equal
  gainIntenMatr[gainIntenMatr >= average_gain] = 1		# tend to
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:60: RuntimeWarning: invalid value encountered in less
  gainIntenMatr[gainIntenMatr < average_gain] = 2			# avoid
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:77: RuntimeWarning: invalid value encountered in double_scalars
  lossIntensity_ij = (arr[i][j]/duration)/np.sum(arr[:,j])
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:80: RuntimeWarning: invalid value encountered in greater_equal
  lossIntenMatr[lossIntenMatr >= np.array(average_loss).T] = 1    # tend

In [3]:
mapArr_96

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
TM_9605

array([[  43,   20,    0,    0,    0,    0,    0],
       [  20, 9444,   11,    0,    0,   87,    0],
       [   0,    6,  129,    0,    0,   31,    0],
       [   0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0],
       [   0,  235,   14,    0,    6, 4939,    0],
       [   0,    1,    0,    0,    3,    0,    0]])

In [5]:
TM_9605pd = ct.transMatrix(mapArr_96,mapArr_05,7)[0]
TM_9605pd

cls_1  cls_2  cls_3  cls_4  cls_5  cls_6  cls_7  row_tot
cls_1       43     20      0      0      0      0      0       63
cls_2       20   9444     11      0      0     87      0     9562
cls_3        0      6    129      0      0     31      0      166
cls_4        0      0      0      0      0      0      0        0
cls_5        0      0      0      0      0      0      0        0
cls_6        0    235     14      0      6   4939      0     5194
cls_7        0      1      0      0      3      0      0        4
col_tot     63   9706    154      0      9   5057      0    14989

In [6]:
gainIntenPtn_9605

array([[nan,  1.,  2.,  1.,  2.,  2.,  1.],
       [ 1., nan,  2.,  1.,  2.,  2.,  1.],
       [ 2.,  2., nan,  1.,  2.,  1.,  1.],
       [ 3.,  3.,  3., nan,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3., nan,  3.,  3.],
       [ 2.,  2.,  1.,  1.,  1., nan,  1.],
       [ 2.,  1.,  2.,  1.,  1.,  2., nan]])

In [7]:
lossIntenPtn_9605

array([[nan,  2.,  2.,  3.,  1.,  2.,  3.],
       [ 1., nan,  1.,  3.,  1.,  2.,  3.],
       [ 2.,  2., nan,  3.,  1.,  2.,  3.],
       [ 2.,  2.,  2., nan,  1.,  2.,  3.],
       [ 2.,  2.,  2.,  3., nan,  2.,  3.],
       [ 2.,  1.,  1.,  3.,  1., nan,  3.],
       [ 2.,  2.,  2.,  3.,  1.,  2., nan]])

In [9]:
result

[                 cls_1      cls_2      cls_3      cls_4      cls_5      cls_6  \
                   Gain Loss  Gain Loss  Gain Loss  Gain Loss  Gain Loss  Gain   
 cls_1 interval_1   NaN  NaN   1.0  2.0   2.0  2.0   1.0  3.0   2.0  1.0   2.0   
       interval_2   NaN  NaN   1.0  2.0   1.0  3.0   1.0  3.0   1.0  3.0   2.0   
       interval_3   NaN  NaN   1.0  2.0   1.0  3.0   1.0  3.0   1.0  3.0   2.0   
 cls_2 interval_1   1.0  1.0   NaN  NaN   2.0  1.0   1.0  3.0   2.0  1.0   2.0   
       interval_2   2.0  1.0   NaN  NaN   1.0  3.0   1.0  3.0   1.0  3.0   2.0   
       interval_3   1.0  2.0   NaN  NaN   1.0  3.0   1.0  3.0   1.0  3.0   1.0   
 cls_3 interval_1   2.0  2.0   2.0  2.0   NaN  NaN   1.0  3.0   2.0  1.0   1.0   
       interval_2   2.0  2.0   1.0  1.0   NaN  NaN   1.0  3.0   1.0  3.0   1.0   
       interval_3   3.0  2.0   3.0  2.0   NaN  NaN   3.0  3.0   3.0  3.0   3.0   
 cls_4 interval_1   3.0  2.0   3.0  2.0   3.0  2.0   NaN  NaN   3.0  1.0   3.0   
       interval_

In [14]:
ct.kappa(result[0],result[1])

0.10460805084745761

In [12]:
result[0].shape

(21, 14)

In [29]:
import CrossTabulation as ct
import ClippingRrasterWithShp as cRs
import numpy as np
import pandas as pd
from sklearn.metrics import cohen_kappa_score
import geopandas as gpd 


lucc1996 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB1996_WH_Erase_Merge_UGB_Dis.tif"
lucc2002 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2002_WH_Erase_Merge_UGB_Dis.tif"
lucc2005 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2005_WH_Erase_Merge_UGB_Dis.tif"
lucc2010 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2010_WH_Erase_Merge_UGB_Dis.tif"
lucc2015 = r"C:\Users\jyang71\Desktop\Datasets\DLTB\DLTB2015_WH_Erase_Merge_UGB_Dis.tif"
clipFc = r"C:\Users\jyang71\Desktop\Datasets\WH_XZQ_Project_Eliminate.shp"
gpdFc1996 = cRs.getLuccArr(lucc1996,clipFc)
gpdFc2002 = cRs.getLuccArr(lucc2002,clipFc)
gpdFc2005 = cRs.getLuccArr(lucc2005,clipFc)
gpdFc2010 = cRs.getLuccArr(lucc2010,clipFc)
gpdFc2015 = cRs.getLuccArr(lucc2015,clipFc)

gpdFc = gpd.read_file(clipFc)

ptnLst = []
shapeLength = gpdFc1996.shape[0]

for i in range(shapeLength):
	mapArr_96 = gpdFc1996.LuccMtx[i][0]
	mapArr_05 = gpdFc2005.LuccMtx[i][0]
	mapArr_10 = gpdFc2010.LuccMtx[i][0]
	mapArr_15 = gpdFc2015.LuccMtx[i][0]
	TM_9605 = ct.transMatrix(mapArr_96,mapArr_05,7)[1]
	gainIntenPtn_9605,lossIntenPtn_9605 = ct.TransPattern(TM_9605,9)
	GainLossPtn_9605 = ct.mergeGainLoss(gainIntenPtn_9605,lossIntenPtn_9605)

	TM_0510 = ct.transMatrix(mapArr_05,mapArr_10,7)[1]
	gainIntenPtn_0510,lossIntenPtn_0510 = ct.TransPattern(TM_0510,5)
	GainLossPtn_0510 = ct.mergeGainLoss(gainIntenPtn_0510,lossIntenPtn_0510)

	TM_1015 = ct.transMatrix(mapArr_10,mapArr_15,7)[1]
	gainIntenPtn_1015,lossIntenPtn_1015 = ct.TransPattern(TM_1015,5)
	GainLossPtn_1015 = ct.mergeGainLoss(gainIntenPtn_1015,lossIntenPtn_1015)

	Ptn = ct.mergeInterval(GainLossPtn_9605,GainLossPtn_0510,GainLossPtn_1015)
	ptnLst.append(list(np.array(Ptn)))

gpdFc['TransPtn'] = ptnLst

C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:56: RuntimeWarning: invalid value encountered in double_scalars
  gainIntensity_ji = (arr[j][i]/duration)/np.sum(arr[j,:])
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:59: RuntimeWarning: invalid value encountered in greater_equal
  gainIntenMatr[gainIntenMatr >= average_gain] = 1		# tend to
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:60: RuntimeWarning: invalid value encountered in less
  gainIntenMatr[gainIntenMatr < average_gain] = 2			# avoid
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:77: RuntimeWarning: invalid value encountered in double_scalars
  lossIntensity_ij = (arr[i][j]/duration)/np.sum(arr[:,j])
C:\Users\jyang71\Desktop\LCM_Pattern_Cluster\LCM_Pattern\CrossTabulation.py:80: RuntimeWarning: invalid value encountered in greater_equal
  lossIntenMatr[lossIntenMatr >= np.array(average_loss).T] = 1    # tend

In [30]:
len(ptnLst)

110

In [31]:
gpdFc.columns

Index(['area', 'xz_ID', 'geometry', 'TransPtn'], dtype='object')

In [34]:
type(gpdFc.TransPtn[0])

list

In [44]:
np.array(gpdFc.TransPtn[0])

array([[nan, nan,  1.,  2.,  2.,  2.,  1.,  3.,  2.,  1.,  2.,  2.,  1.,
         3.],
       [nan, nan,  1.,  2.,  1.,  3.,  1.,  3.,  1.,  3.,  2.,  2.,  1.,
         3.],
       [nan, nan,  1.,  2.,  1.,  3.,  1.,  3.,  1.,  3.,  2.,  2.,  1.,
         3.],
       [ 1.,  1., nan, nan,  2.,  1.,  1.,  3.,  2.,  1.,  2.,  2.,  1.,
         3.],
       [ 2.,  1., nan, nan,  1.,  3.,  1.,  3.,  1.,  3.,  2.,  2.,  1.,
         3.],
       [ 1.,  2., nan, nan,  1.,  3.,  1.,  3.,  1.,  3.,  1.,  1.,  1.,
         3.],
       [ 2.,  2.,  2.,  2., nan, nan,  1.,  3.,  2.,  1.,  1.,  2.,  1.,
         3.],
       [ 2.,  2.,  1.,  1., nan, nan,  1.,  3.,  1.,  3.,  1.,  2.,  1.,
         3.],
       [ 3.,  2.,  3.,  2., nan, nan,  3.,  3.,  3.,  3.,  3.,  2.,  3.,
         3.],
       [ 3.,  2.,  3.,  2.,  3.,  2., nan, nan,  3.,  1.,  3.,  2.,  3.,
         3.],
       [ 3.,  2.,  3.,  2.,  3.,  3., nan, nan,  3.,  3.,  3.,  2.,  3.,
         3.],
       [ 3.,  2.,  3.,  2.,  3.,  3., nan, 

In [28]:
list(Ptn)

[('cls_1', 'Gain'),
 ('cls_1', 'Loss'),
 ('cls_2', 'Gain'),
 ('cls_2', 'Loss'),
 ('cls_3', 'Gain'),
 ('cls_3', 'Loss'),
 ('cls_4', 'Gain'),
 ('cls_4', 'Loss'),
 ('cls_5', 'Gain'),
 ('cls_5', 'Loss'),
 ('cls_6', 'Gain'),
 ('cls_6', 'Loss'),
 ('cls_7', 'Gain'),
 ('cls_7', 'Loss')]

In [49]:
ct.kappa(np.array(gpdFc.TransPtn[3]),np.array(gpdFc.TransPtn[4]))

0.41805721096543513

In [47]:
for i in range(110):
    print(np.array(gpdFc.TransPtn[i]))

[[nan nan  1.  2.  2.  2.  1.  3.  2.  1.  2.  2.  1.  3.]
 [nan nan  1.  2.  1.  3.  1.  3.  1.  3.  2.  2.  1.  3.]
 [nan nan  1.  2.  1.  3.  1.  3.  1.  3.  2.  2.  1.  3.]
 [ 1.  1. nan nan  2.  1.  1.  3.  2.  1.  2.  2.  1.  3.]
 [ 2.  1. nan nan  1.  3.  1.  3.  1.  3.  2.  2.  1.  3.]
 [ 1.  2. nan nan  1.  3.  1.  3.  1.  3.  1.  1.  1.  3.]
 [ 2.  2.  2.  2. nan nan  1.  3.  2.  1.  1.  2.  1.  3.]
 [ 2.  2.  1.  1. nan nan  1.  3.  1.  3.  1.  2.  1.  3.]
 [ 3.  2.  3.  2. nan nan  3.  3.  3.  3.  3.  2.  3.  3.]
 [ 3.  2.  3.  2.  3.  2. nan nan  3.  1.  3.  2.  3.  3.]
 [ 3.  2.  3.  2.  3.  3. nan nan  3.  3.  3.  2.  3.  3.]
 [ 3.  2.  3.  2.  3.  3. nan nan  3.  3.  3.  2.  3.  3.]
 [ 3.  2.  3.  2.  3.  2.  3.  3. nan nan  3.  2.  3.  3.]
 [ 2.  2.  1.  2.  1.  3.  1.  3. nan nan  2.  2.  1.  3.]
 [ 3.  2.  3.  2.  3.  3.  3.  3. nan nan  3.  2.  3.  3.]
 [ 2.  2.  2.  1.  1.  1.  1.  3.  1.  1. nan nan  1.  3.]
 [ 1.  1.  2.  1.  1.  3.  1.  3.  1.  3. nan nan  1.  3